"""
Pull hiring manager feedback from Ashby notes and pair with AI screening results.

Scans candidates who reached Screened stage (or beyond), pulls their notes,
filters to only notes written by hiring team members, and pairs each note
with the AI's verdict/reasoning from screening_log.csv.

Output: a structured feedback report that can be used to calibrate the screening prompt.

Usage:
  python3 pull_hm_feedback.py                    # pull all HM feedback
  python3 pull_hm_feedback.py --since 2026-04-01 # only feedback after this date
  python3 pull_hm_feedback.py --json              # output as JSON (for prompt ingestion)
  python3 pull_hm_feedback.py --dry-run           # preview: show which candidates have HM notes
"""

from __future__ import annotations

import argparse
import csv
import json
import logging
import os
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

logging.basicConfig(level=logging.INFO, format="%(asctime)s  %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger(__name__)

_DIR = Path(__file__).resolve().parent
SCREENING_LOG = _DIR / "screening_log.csv"
FEEDBACK_OUTPUT = _DIR / "hm_feedback.json"

# ── Hiring team: only notes from these people count as feedback ──
# Matched by first name (case-insensitive) from note author field.
# Update this list when hiring team changes.
HIRING_TEAM_FIRST_NAMES = {
    "nischal",
    "arun",
    "emmanuel",
    "tara",
    "kendra",
    "ben",
}


def _is_hiring_team(author: dict) -> bool:
    """Check if a note author is on the hiring team."""
    first = (author.get("firstName") or "").strip().lower()
    return first in HIRING_TEAM_FIRST_NAMES


def _is_ai_note(content: str) -> bool:
    """Check if a note was generated by the AI screening pipeline."""
    if not content:
        return False
    markers = [
        "AI Screening Result:",
        "Screened by AI pipeline",
        "<b>Company:</b>",
        "<b>Summary:</b>",
        "[Imported from Notion",
        "Submitted via /intake",
    ]
    return any(m in content for m in markers)


# ── Load screening log ────────────────────────────────────────────

def load_screening_log() -> Dict[str, dict]:
    """Load screening log keyed by ashby_candidate_id."""
    by_id = {}
    if not SCREENING_LOG.exists():
        return by_id
    with open(SCREENING_LOG, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            cid = (row.get("ashby_candidate_id") or "").strip()
            if cid:
                by_id[cid] = row
    return by_id


# ── Pull candidates from Ashby ────────────────────────────────────

def get_screened_candidates() -> List[dict]:
    """Get Ashby-native candidates who have been screened.

    Only includes candidates screened through the Ashby pipeline (mode='csv'),
    skips legacy backfills to avoid thousands of unnecessary API calls.
    Returns list of {candidate_id, name, verdict, ...}.
    """
    log = load_screening_log()
    candidates = []
    seen = set()
    for cid, row in log.items():
        if cid in seen:
            continue
        seen.add(cid)
        # Skip legacy backfills — only scan Ashby-native candidates
        mode = (row.get("mode") or "").strip()
        if mode.startswith("backfill"):
            continue
        verdict = (row.get("verdict") or "").strip()
        if not verdict or verdict.upper() in ("SCREENING", "SCREENING…"):
            continue
        candidates.append({
            "candidate_id": cid,
            "name": row.get("name", ""),
            "verdict": verdict,
            "spark": row.get("spark", ""),
            "verdict_reason": row.get("verdict_reason", ""),
            "best_fit_role": row.get("best_fit_role", ""),
            "concerns": row.get("concerns", ""),
            "screener_brief": row.get("screener_brief", ""),
            "target_role": row.get("target_role", ""),
            "source": row.get("source", ""),
            "timestamp": row.get("timestamp", ""),
        })
    return candidates


def pull_hm_notes(candidate_id: str, since: Optional[str] = None) -> List[dict]:
    """Pull HM notes for a candidate. Returns list of {author, content, date}."""
    from ashby_bridge import _ashby_post

    result = _ashby_post("candidate.listNotes", {"candidateId": candidate_id})
    notes = result.get("results", [])

    hm_notes = []
    for note in notes:
        author = note.get("author", {})
        content = note.get("content", "")
        created = note.get("createdAt", "")

        # Skip non-HM authors — but allow backfilled notes tagged as HM
        # (these carry "[HM Feedback – ...]" prefix and "AUTHOR: Hiring Manager" sentinel,
        # but were written by the API user, so author-based check fails)
        is_backfill_hm = ("[HM Feedback –" in content) or ("AUTHOR: Hiring Manager" in content)
        if not _is_hiring_team(author) and not is_backfill_hm:
            continue

        # Skip AI-generated notes (in case an HM account was used for automation)
        if _is_ai_note(content):
            continue

        # Skip empty notes
        if not content.strip():
            continue

        # Date filter
        if since and created:
            try:
                note_date = datetime.fromisoformat(created.replace("Z", "+00:00"))
                since_date = datetime.fromisoformat(since + "T00:00:00+00:00")
                if note_date < since_date:
                    continue
            except (ValueError, TypeError):
                pass

        hm_notes.append({
            "author": f"{author.get('firstName', '')} {author.get('lastName', '')}".strip(),
            "content": content,
            "date": created[:10] if created else "",
        })

    return hm_notes


# ── Main ──────────────────────────────────────────────────────────

def pull_feedback(since: Optional[str] = None, dry_run: bool = False, as_json: bool = False):
    """Pull all HM feedback paired with AI screening results."""
    from ashby_bridge import _ashby_post

    candidates = get_screened_candidates()
    print(f"\n  Scanning {len(candidates)} screened candidates for HM feedback...\n")

    feedback_pairs = []
    checked = 0
    with_feedback = 0

    for c in candidates:
        cid = c["candidate_id"]
        name = c["name"]
        checked += 1

        hm_notes = pull_hm_notes(cid, since=since)
        if not hm_notes:
            continue

        with_feedback += 1

        if dry_run:
            for note in hm_notes:
                print(f"  {name:<35} {c['verdict']:<15} note by {note['author']} ({note['date']})")
            continue

        pair = {
            "candidate": {
                "name": name,
                "role": c.get("target_role", ""),
                "source": c.get("source", ""),
            },
            "ai_screening": {
                "verdict": c["verdict"],
                "spark": c.get("spark", ""),
                "verdict_reason": c.get("verdict_reason", ""),
                "best_fit_role": c.get("best_fit_role", ""),
                "concerns": c.get("concerns", ""),
                "screener_brief": c.get("screener_brief", ""),
            },
            "hm_feedback": hm_notes,
        }
        feedback_pairs.append(pair)

        for note in hm_notes:
            print(f"  {name:<35} {c['verdict']:<15} ← {note['author']} ({note['date']})")

        # Rate limit
        if checked % 20 == 0:
            time.sleep(0.5)

    print(f"\n  Summary:")
    print(f"    Candidates checked:    {checked}")
    print(f"    With HM feedback:      {with_feedback}")
    print(f"    Total feedback notes:  {sum(len(p['hm_feedback']) for p in feedback_pairs)}")

    if feedback_pairs and not dry_run:
        if as_json:
            output = json.dumps(feedback_pairs, indent=2, ensure_ascii=False)
            FEEDBACK_OUTPUT.write_text(output, encoding="utf-8")
            print(f"\n  Written to {FEEDBACK_OUTPUT}")
        else:
            # Print readable summary
            print(f"\n  {'='*70}")
            print(f"  HIRING MANAGER FEEDBACK REPORT")
            print(f"  {'='*70}\n")
            for pair in feedback_pairs:
                c = pair["candidate"]
                ai = pair["ai_screening"]
                print(f"  Candidate: {c['name']}")
                print(f"  Role: {c.get('role', 'N/A')}")
                print(f"  AI Verdict: {ai['verdict']}")
                if ai.get("spark"):
                    print(f"  AI Spark: {ai['spark'][:200]}")
                if ai.get("concerns"):
                    print(f"  AI Concerns: {ai['concerns'][:200]}")
                print()
                for note in pair["hm_feedback"]:
                    print(f"    HM ({note['author']}, {note['date']}):")
                    # Indent note content
                    for line in note["content"].split("\n"):
                        print(f"      {line}")
                    print()
                print(f"  {'-'*50}\n")

    return feedback_pairs


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pull HM feedback from Ashby notes")
    parser.add_argument("--since", default=None,
                        help="Only pull feedback after this date (YYYY-MM-DD)")
    parser.add_argument("--json", action="store_true",
                        help="Output as JSON file (for prompt ingestion)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Preview which candidates have HM notes")
    args = parser.parse_args()

    if not os.environ.get("ASHBY_API_KEY"):
        print("\nMissing ASHBY_API_KEY. Set it: export ASHBY_API_KEY='...'")
        sys.exit(1)

    pull_feedback(since=args.since, dry_run=args.dry_run, as_json=args.json)
